language: generic  
sudo: required # docker require sudo permission 
services: 
  - docker     # tell travis we need a docker container 
# any command we can run before we start to deploy our project or do the test 
# in this case, we can build our docker image 
before_install: 
  - docker build ./client -f ./client/Dockerfile.dev -t tsuweiquan/sec10-react-test 
# The job to be executed 
# -e is extra 
# CI=true is used to suppress an exorbitant amount of verbose console outputs  
script: 
  - docker run -e CI=true tsuweiquan/sec10-react-test npm run test -- --coverage

after_success:
  - docker build -t tsuweiquan/sec10-client ./client
  - docker build -t tsuweiquan/sec10-server ./server
  - docker build -t tsuweiquan/sec10-worker ./worker
  - docker build -t tsuweiquan/sec10-nginx ./nginx
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tsuweiquan/sec10-client
  - docker push tsuweiquan/sec10-server
  - docker push tsuweiquan/sec10-worker
  - docker push tsuweiquan/sec10-nginx
# now we upload the images to docker hub

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-686881272567'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $aws_access_id
  secret_access_key: $aws_secret_id